version: "3.9"  # optional since v1.27.0
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    restart: always
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
      - mongodb
    ports:
      - "3001:80"
