export enum GameState {
  WAITING_ROOM = "WAITING_ROOM",
  PLAYING_PLAYFIELD = "PLAYING_PLAYFIELD",
  PLAYING_BRAINSTORM = "PLAYING_BRAINSTORM",
  PLAYING_IDEA_SELECTION = "PLAYING_IDEA_SELECTION",
  WINNER_ANNOUNCEMENT = "WINNER_ANNOUNCEMENT",
}
