export const NEW_ROOM_ACTION = "new-room"
export const JOIN_ROOM_ACTION = "join-room"
export const START_GAME_ACTION = "start-game"
export const SWAP_CARDS_ACTION = "swap-cards"
export const PLAY_CARD_ACTION = "play-card"
